pybo/views/answer_views.py
from datetime import datetime

from flask import Blueprint, flash, g, render_template, request, url_for
from pybo import db
from pybo.forms import AnswerForm
from pybo.models import Answer, Question
from pybo.views.auth_views import login, login_required
from werkzeug.utils import redirect

bp = Blueprint('answer', __name__, url_prefix='/answer')


@bp.route('/create/<int:question_id>', methods=('POST',))
@login_required
def create(question_id):
    form=AnswerForm()
    question=Question.query.get_or_404(question_id)
    if form.validate_on_submit():
        
        content = request.form['content']
        answer = Answer(question=question, content=content, create_date=datetime.now(),user=g.user)
        db.session.add(answer)
        db.session.commit()
        # '{} = url 과 id가 들어가야함
        # '{}#answer_{}'.format(   ,answer.id) 
        return redirect('{}#answer_{}'.format(
            url_for('question.detail', question_id=question_id),answer.id) )
    return render_template('question/question_detail.html',question=question,form=form)
@bp.route('/modify/<int:answer_id>',methods=('GET','POST'))
@login_required
def modify(answer_id):
    answer=Answer.query.get_or_404(answer_id)
    if g.user != answer.user:
        flash('수정권한이 없습니다')
        return redirect(url_for('question.detail',question_id=answer.question.id))
    if request.method=='POST':
        form=AnswerForm()
        if form.validate_on_submit():
            form.populate_obj(answer)
            answer.modify_date=datetime.now()
            db.session.commit()
                    # '{} = url 과 id가 들어가야함
        # '{}#answer_{}'.format(   ,answer.id) 
            return redirect('{}#answer_{}'.format(
                url_for('question.detail',question_id=answer.question.id),answer.id) )
    else:
        form=AnswerForm(obj=answer)
    return render_template('answer/answer_form.html',form=form)
            
@bp.route('/delete/<int:answer_id>')
@login_required
def delete(answer_id):
    answer=Answer.query.get_or_404(answer_id)
    question_id=answer.question.id
    if g.user !=answer.user:
        flash('수정권한x')
    else:
        db.session.delete(answer)
        db.session.commit()
        
    return redirect(url_for('question.detail',question_id=question_id))
@bp.route('/vote/<int:answer_id>/')
@login_required
def vote(answer_id):
    _answer=Answer.query.get_or_404(answer_id)
    if g.user==_answer.user:
        flash('본인이 작성한글은 x')
    else:
        _answer.voter.append(g.user)
        db.session.commit()
              # '{} = url 과 id가 들어가야함
        # '{}#answer_{}'.format(   ,answer.id) 
    return redirect('{}#answer_{}'.format(
        url_for('question.detail',question_id=_answer.question.id),_answer.id))

pybo/views/question_views.py
from datetime import datetime
from math import e
from re import sub

from flask import Blueprint, flash, g, render_template, request, url_for
from pybo import db
from pybo.forms import AnswerForm, QuestionForm
from pybo.models import Answer, Question, User
from pybo.views.auth_views import login_required
from werkzeug.utils import redirect

bp = Blueprint('question', __name__, url_prefix='/question')
# url_preflix에 / 를안붙였으므로 /붙여야함 앞뒤로 /가 나와야 작동!!
# /question/면 detail 만함

@bp.route('/list/')
def _list():
    page=request.args.get('page',type=int,default=1)
    kw=request.args.get('kw',type=str,default='')
    question_list = Question.query.order_by(Question.create_date.desc())
    # url 쿼리 파라미터에서 가져올거 url통해서 가져오는거기때문에 views저의해주어햐마
    # default=1이기때문에 자동으로 ?page=1이되어서 받아온느거 없으면 안됨 ?page= 이래버림
    if kw:
        search='%%{}%%'.format(kw)
        sub_query=db.session.query(Answer.quesiton_id,Answer.content,User.username) \
            .join(User,Answer.user_id==User.id).subquery()
        # 필드 명시선언하면 그필드만가져오고
        # 명시선언안할시 전체가져옴
        question_list=question_list \
            .join(User) \
            .outerjoin(sub_query,sub_query.c.quesiton_id==Question.id) \
            .filter(Question.subject.ilike(search) |
                    Question.content.ilike(search) |
                    User.username.ilike(search) |
                    sub_query.c.content.ilike(search) |
                    sub_query.c.username.ilike(search)
                    ) \
            .distinct()
            # 같은거니까 Answer.content,Answer.Username,Answer.question_id가 오른쪽에 붙는다
    
    
    question_list=question_list.paginate(page=page,per_page=10)
    return render_template('question/question_list.html', question_list=question_list)


@bp.route('/detail/<int:question_id>/')
def detail(question_id):
    # 처음부터들어갈경우
    form=AnswerForm()
    question = Question.query.get_or_404(question_id)
    # answer_view에서 form을 전달했는데 여기서 안하면 에러 null 이되버림 연동되는게아니라서
    # 다써줘야함
    return render_template('question/question_detail.html', question=question,form=form) 

# render post를하는 디폴드url을 가지고있는데 이 디폴트 url은 기본적으로
# post를 못받음 그러므로 써줘야함
# 하지만 지금 route에서 post를 받는다고 써있지않기때문에 오류

@bp.route('/create/',methods=('GET','POST'))
@login_required
def create():
    # 함수바로위에 해야함
    # 기본적으로 get이기때문에 if post를 써줭햐ㅏㅁ
    
    form=QuestionForm()
    if request.method == 'POST'  and form.validate_on_submit():
        question = Question(subject=form.subject.data, content=form.content.data, create_date=datetime.now(),user=g.user)
        # 전역변수 g에 저장된걸 가져온다
        db.session.add(question)
        db.session.commit()
        return redirect(url_for('main.index'))
    return render_template('question/question_form.html',form=form)


@bp.route('/modify/<int:question_id>',methods=('GET','POST'))
@login_required
# login_required는 view만담고 라우팅은 못잡어넣음
def modify(question_id):
    question=Question.query.get_or_404(question_id)
    
    if g.user !=question.user:
        flash('수정권한x')
        return redirect(url_for('question.detail',question_id=question_id))
    if request.method=='POST':
        form=QuestionForm()
        if form.validate_on_submit():
            form.populate_obj(question)
            question.modify_date=datetime.now()
            db.session.commit()
            # 아직 add하는거아님
            return redirect(url_for('question.detail',question_id=question_id))
    else:
        form=QuestionForm(obj=question)
    return render_template('question/question_form.html',form=form)    

@bp.route('/delete/<int:question_id>')
@login_required
def delete(question_id):
    question=Question.query.get_or_404(question_id)
    if g.user != question.user:
        flash('수정권한x')
        return redirect(url_for('question.detail',question_id=question_id))
    db.session.delete(question)
    db.session.commit()
    # commit 변경점 적용
    return redirect(url_for('question._list'))


@bp.route('/voter/<int:question_id>')
@login_required
def vote(question_id):
# def view 매개함수에는 route로부터 받는거임
# route가 views가있으면 view 받느넉고
    _question=Question.query.get_or_404(question_id)
    if g.user == _question.user:
        flash('본인추천x')
    else:
        _question.voter.append(g.user)
        db.session.commit()
    return redirect(url_for('question.detail',question_id=question_id))

pybo/templates/question/question_detail.html
{% extends "base.html" %}
{% block content %}
<!--css는 url 추적함수라고 봐야하고, 정적파일도 찾아준다고봐야한다
 url_for는 추적함수라고 보자 라우팅함수의 url을 추적함 폴더와 파일을 쓴다-->
<div class="container">
    <!--질문-->
    <h2 class="border-bottom py-2">{{question.subject}} </h2>
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space:pre-line ;">{{question.content}} </div>
                <div class="d-flex justify-content-end">

                    {% if question.modify_date %}
                    <div class="badge bg-light text-dark p-2 text-start mx-3">
                        <div class="mb-2">modified_at</div>
                        <div>{{question.modify_date|datetime}} </div>
                    </div>
                    {% endif %}

                    <div class="badge bg-light text-dark p-2 text-start"> 
                    <div class="mb-2">{{question.user.username}} </div>
                    <div>{{question.create_date|datetime}}</div>
                </div>

            </div>
            <div class="my-3">
                <a href="javascript:void(0)" data-uri="{{url_for("question.vote",question_id=question.id)}}" 
                class="recommend btn btn-sm btn-outline-secondary">추천
                <span class="badge rounded-pill bg-success">{{question.voter|length}} </span>
            </a>
            <!--bg백그 lg라지 sm스몰-->
                <!--secondary=회색-->
                {% if g.user==question.user %}
                <a href="{{url_for("question.modify",question_id=question.id)}}"
                 class="btn btn-sm btn-outline-secondary">수정</a>
                <a href="javascript:void(0)" class="delete btn btn-sm btn-outline-secondary"
                    data-uri="{{url_for("question.delete",question_id=question.id)}}">삭제</a>
                
                {% endif %}
                
            </div>

        </div>
    </div>
    <!--답변-->
    <h5 class="border-bottom my-3 py-2">{{question.answer_set|length}} 개의 답변이있음 </h5>

    {% for answer in question.answer_set %}
    <a id="answer_{{answer.id}}"></a>
    <!--answer.id 를 찾아서 view에 넣는거 id는 view와 공유하기때문 -->
    <div class="card my-3">
            <div class="card-body">
                <div class="card-text" style="white-space:pre-line ;">{{answer.content}}</div>
                <div class="d-flex justify-content-end">
                    {% if answer.modify_date %}
                    <div class="badge bg-light text-dark p-2 text-start mx-3">
                        <div class="mb-2"> modified_at</div>
                        <div>{{answer.modify_date|datetime}} </div>
                    </div>
                    {% endif %}
                    <div class="badge bg-light text-dark p-2 text-start">
                        <div>{{answer.user.username}} </div>
                        <div>{{answer.create_date|datetime}}</div>
                    </div>

                </div>
                <div class="my-3">
                    <a href="javascript:void(0)" data-uri="{{url_for("answer.vote",answer_id=answer.id)}}"
                    class="recommend btn btn-sm btn-outline-secondary">추천
                <span class="badge rounded-pill bg-success">{{answer.voter|length}} </span></a>
                    {% if g.user==answer.user %}
                        <a href="{{url_for("answer.modify",answer_id=answer.id)}}" class="btn btn-sm btn-outline-secondary">수정</a>
                    
                        <a href="javascript:void(0)" class="delete btn btn-sm btn-outline-secondary"
                        data-uri="{{url_for("answer.delete",answer_id=answer.id)}}" >삭제</a>
                        {% endif %}
                </div>
            </div>
        </div>

    {% endfor %}    
       <!--등록-->
        <form action="{{url_for("answer.create",question_id=question.id)}}" method="post" class="my-3">
            {{form.csrf_token}}
            {% if form.errors %}
            <div class="alert alert-danger" role="alert">
                <!--키값, value면 items()로 -->
                {% for field,errors in form.errors.items() %}

                <strong>{{form[field].label}} </strong>
                <ul>
                    {% for error in errors %}
                    <li>{{error}} </li>
                    {% endfor %}
                </ul>
                {% endfor %}
            </div>
            {% endif %}
            <div class="mb-3">
                <textarea {% if not g.user %}disabled{% endif %}
                name="content" id="content" class="form-control" rows="10"></textarea>
                <input type="submit" value="답변등록" class="btn btn-primary">
            </div>

        </form>

</div>



{% endblock  %}
{% block script %}
<script type="text/javascript">

const delete_elements=document.getElementsByClassName("delete");
Array.from(delete_elements).forEach(function(element){
    element.addEventListener('click',function(){
        if(confirm('정말삭제?')){
            location.href=this.dataset.uri
        }

    });
});
const recommend_elements=document.getElementsByClassName("recommend");
Array.from(recommend_elements).forEach(function(element){
    element.addEventListener('click',function(){
        if(confirm('정말추천?')){
            location.href=this.dataset.uri
        }

    });
});

</script>

{% endblock  %}

pybo/templates/question/question_form.html
{% extends "base.html" %}
{% block content %}
<div class="container">
    {% for message in get_flashed_messages()  %}
    <div class="alert alert-danger" role="alert">
        <strong>{{message}} </strong>
    </div>
    {% endfor %}
    <h5 class="my-3 border-bottom py-2">
        <!--my-3는 전 py 는 그 후라고 생각하자 그사이는 객체이고-->
        질문등록
        <form class="post-form my-3" method="post">
            {{form.csrf_token}}
            {% if form.errors %}
                <div class="alert alert-danger" role="alert">
                    {% for field,errors in form.errors.items() %}
                    
                    <strong>{{form[field].label}} </strong>
                    {% for error in errors %}
                    <li>{{error}}</li>
                    {% endfor %}
                    {% endfor %}
                </div>

            {% endif %}
            <!--나중을위해 action url안씀-->
            <!--action지정안할시 자기를 호출한 views로 자동호출-->
            <!--즉 question.create가 자동됨-->
            <div class="mb-3">
                <label for="subject">제목</label>
                <input class="form-control" type="text" name="subject" id="subject"
                value="{{form.subject.data or ''}}">
            </div>
            <div class="mb-3">
                <label for="content">내용</label>
                <textarea class="form-control" name="content" id="content" rows="10">{{form.content.data or ''}}</textarea>
            </div>
            <button type="submit" class="btn btn-primary">저장하기</button>

        </form>
    </h5>

</div>

{% endblock  %}

pybo/templates/question/question_list.html
{% extends "base.html" %}
{% block content %}
<div class="container my-3">
  <!-- c 자동완성이 주석 -->
   <div class="row my-3">
      <div class="col-6">
        <a href="{{url_for("question.create")}}" class="btn btn-primary" >질문등록하기</a>
      </div>
      <div class="col-6">
          <div class="input-group">
            <input type="text"  id="search_kw" class="form-control" value="{{kw or ''}}">
            <div class="input-group-append">
                <button type="button" class="btn btn-outline-secondary" id="btn_search">찾기</button>
            </div>
          </div>
      </div>
   </div>
    <table class="table">
        <thead class="text-center table-dark ">
            <tr>
                <th >번호</th>
                <th style="width:50%">제목</th>
                <th>글쓴이</th>
                <th>작성일시</th>
            </tr>
        </thead>
        <tbody>
            {% if question_list %}
            <!--목록가져오려면 .items해줘야함-->
            {% for question in question_list.items %}
            <tr class="text-center">
                <td>{{question_list.total -((question_list.page-1)*question_list.per_page)-loop.index0 }} </td>
                <td class="text-start">
                    <a href="{{url_for("question.detail",question_id=question.id)}}">{{question.subject}} </a>
                    {% if question.answer_set|length > 0 %}
                    <span class="text-danger small mx-2">{{question.answer_set|length}} </span>
                    {% endif %}
                </td>
                <td>
                  {{question.user.username}}
                </td>
                <td>
                    {{question.create_date|datetime}}
                </td>
            </tr>
            
            {% endfor %}
            {% else %}
            <tr>
                <td colspan="3">질문x</td>
            </tr>
            {% endif %}

        </tbody>
    </table>

      <ul class="pagination justify-content-center">
        <!--이전-->
        {% if question_list.has_prev %}
        <li class="page-item">
          <a class="page-link" href="javascript:void(0)" data-page="{{question_list.prev_num}}">이전
          </a>
        </li>
        {% else %}
        <li class="page-item disabled">
          <a class="page-link" tabindex="-1"  href="javascript:void(0)">이전
          </a>
        </li>
        {% endif %}
                <!--이전-->
                <!--페이지번호-->
                <!--?page=1로 href로 가능하지만
                javascript로 막아버릴경우 javascript에서 hidden으로 id 'page' input hidden필드에 클릭된 페이지번호를 설정후
                form을 submit함 이게규칙 쿼리스트링이아닌 폼데이터로 전송 href url에 속성넣어 보내는게 쿼리스트링이라고함-->
        <!--주소 /옆에 ?는 원래 나오는거임 view로 따로정의안하고 속성값이들어갈때-->
        {% for page_num in question_list.iter_pages() %}
        {% if page_num %}
        {% if page_num !=question_list.page %}
        <li class="page-item"><a class="page-link" href="javascript:void(0)" data-page="{{page_num}}" >{{page_num}} </a></li>
        {% else %}
        <li class="page-item active"><a class="page-link" href="#">{{page_num}} </a></li>
        {% endif %}
        {% else %}
        <li class="disabled">
          <a class="page-link" href="javascript:void(0)" >...</a>
        </li>
        {% endif %}
        {% else %}
 
        {% endfor %}
        <!--페이지번호-->

          <!--다음-->
                {% if question_list.has_next %}
        <li class="page-item">
          <a class="page-link" href="javascript:void(0)" data-page="{{question_list.next_num}}" >다음
          </a>
        </li>
        {% else %}
        <li class="page-item disabled">
          <a class="page-link" href="javascript:void(0)" >다음
        </li>
        {% endif %}
               <!--다음-->
      </ul>
    
</div>
<form action="" id="searchForm" method="get">
  <!-- kw와 page가 url에 나옴 get이라서 hidden 취급 form get한순간부터 url에 나타남 -->
  <input type="text" name="kw" id="kw" value="{{kw or ''}}">
  <input type="text" name="page" id="page" value="{{page}}">
</form>
<!-- page-link안에서 'page'를 찾는게아닌 독립적으로 'page'를 찾음 for쓴게아니기때문 -->
{% endblock  %}
{% block script %}
<script type="text/javascript">
  const page_elements=document.getElementsByClassName("page-link");
  Array.from(page_elements).forEach(function(element){
      element.addEventListener('click',function(){
          document.getElementById('page').value=this.dataset.page;
          document.getElementById('searchForm').submit()
      });
  });
  const btn_search=document.getElementById("btn_search");
  btn_search.addEventListener('click',function(){
        document.getElementById('kw').value=document.getElementById('search_kw').value;
        document.getElementById('page').value=1;
        document.getElementById('searchForm').submit();

    });

</script>
{% endblock  %}